### ISSUE TITLE
Building View Styling

### ISSUE THREAD

**Issue by ghost** [YaleDHLab/nhba#112]
![nhba-building view-expand 1](https://cloud.githubusercontent.com/assets/25487/26114807/4e238a50-3a2c-11e7-9c34-74b6952ac576.png)
Comp of Building View

- [ ] Gallery / Map toggle text: font-size: .8em / font-weight: 500 / color #999999
- [ ] Left sidebar links:  color: #999 / font-weight: 500 / font-size: .95 em / helvetica neue
- [ ] .building-button .label { vertical-align: middle / margin-top: -8px }
- [ ] increase margin to the right of the .building-button-icon to about 14px
- [ ] Suggest and Edit button text: font-size: .95em / font-weight: 500 
- [ ] Building metadata and description text on the right side: .825 em / color #666 / weight: 400
- [ ] Building info headings: YaleNew Roman
